coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: false

ignore:
  - "archive/**"
  - "tests/**"
