[package]
name = "g-input"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ahash = { workspace = true }
csv = { workspace = true }
g-plan = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "alignment"
harness = false

[lints]
workspace = true
