[package]
name = "g-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
g-engine = { workspace = true }
g-interface = { workspace = true }
g-plan = { workspace = true }
g-runtime = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
g-genotype = { workspace = true }
g-input = { workspace = true }

[lints]
workspace = true
