import os.path

def build( bld ):
	sources = bld.path.ant_glob( 'src/*.cpp' )
	bld.stlib(
		target = 'db',
		source = sources,
		includes='./include',
		cxxflags = [ '-std=c++11'],
		use = 'boost sqlite3',
		export_includes = './include'
	)
