from collections.abc import Sequence

class cli:  # noqa: N801 - extension submodule name
    class NativeCliRunResult:
        @property
        def exit_code(self) -> int: ...
        @property
        def stdout_chunks(self) -> tuple[str, ...]: ...
        @property
        def stderr_chunks(self) -> tuple[str, ...]: ...

    @staticmethod
    def run(arguments: Sequence[str]) -> NativeCliRunResult: ...
