import typing
from collections.abc import Sequence

class cli:  # noqa: N801 - extension submodule name
    class NativeCliRunResult:
        @property
        def exit_code(self) -> int: ...
        @property
        def stdout_chunks(self) -> tuple[str, ...]: ...
        @property
        def stderr_chunks(self) -> tuple[str, ...]: ...

    @staticmethod
    def run(arguments: Sequence[str]) -> NativeCliRunResult: ...

class engine:  # noqa: N801 - extension submodule name
    class JaxBackendConfig:
        @property
        def association_mode(self) -> str: ...
        @property
        def score_dtype(self) -> str: ...
        @property
        def firth_dtype(self) -> str: ...
        @property
        def correction_method(self) -> str: ...
        @property
        def correction_p_threshold(self) -> float: ...
        @property
        def firth_se(self) -> bool: ...
        @property
        def linear_minimum_variance(self) -> float: ...
        @property
        def linear_relative_variance_tolerance(self) -> float: ...
        @property
        def binary_minimum_probability(self) -> float: ...
        @property
        def binary_minimum_variance(self) -> float: ...
        @property
        def binary_relative_variance_tolerance(self) -> float: ...
        @property
        def binary_null_maximum_iterations(self) -> int: ...
        @property
        def binary_null_coefficient_tolerance(self) -> float: ...
        @property
        def firth_batch_size(self) -> int: ...
        @property
        def firth_candidate_capacity(self) -> int: ...
        @property
        def firth_maximum_iterations(self) -> int: ...
        @property
        def firth_gradient_tolerance(self) -> float: ...
        @property
        def firth_coefficient_tolerance(self) -> float: ...
        @property
        def firth_likelihood_tolerance(self) -> float: ...
        @property
        def firth_maximum_step_size(self) -> float: ...
        @property
        def firth_pseudo_maximum_iterations(self) -> int: ...
        @property
        def firth_pseudo_inner_maximum_iterations(self) -> int: ...
        @property
        def firth_newton_raphson_zero_start_iterations(self) -> int: ...
        @property
        def firth_line_search_maximum_attempts(self) -> int: ...
        @property
        def firth_step_halving_maximum_attempts(self) -> int: ...
        @property
        def firth_initial_response_scale(self) -> float: ...
        @property
        def firth_sparse_carrier_dosage_threshold(self) -> float: ...
        @property
        def firth_step_halving_scale(self) -> float: ...
        @property
        def use_block_firth_math(self) -> bool: ...
        @property
        def null_firth_maximum_iterations(self) -> int: ...
        @property
        def null_firth_gradient_tolerance(self) -> float: ...
        @property
        def null_firth_maximum_step_size(self) -> float: ...
        @property
        def null_firth_fallback_iteration_multiplier(self) -> int: ...
        @property
        def null_firth_fallback_step_divisor(self) -> float: ...
        @property
        def null_firth_line_search_maximum_attempts(self) -> int: ...
        @property
        def null_firth_step_halving_scale(self) -> float: ...

    class JaxGroupInput:
        @property
        def phenotype_matrix(self) -> typing.Any: ...
        @property
        def covariate_matrix(self) -> typing.Any: ...

    class JaxChromosomeInput:
        @property
        def prediction_matrix(self) -> typing.Any: ...

    class JaxGenotypeBatch:
        @property
        def variant_start_index(self) -> int: ...
        @property
        def dosage_matrix(self) -> typing.Any | None: ...
        @property
        def packed8_probabilities(self) -> typing.Any | None: ...
        @property
        def dosage_sum(self) -> typing.Any: ...
        @property
        def observation_count(self) -> typing.Any: ...
        @property
        def imputed_dosage_square_sum(self) -> typing.Any | None: ...
        @property
        def rare_sparse_mask(self) -> typing.Any | None: ...

    class JaxMaterializationRequest:
        @property
        def active_trait_indices(self) -> list[int]: ...
        @property
        def output_statistic_dtype(self) -> str: ...

    class JaxNullModelDiagnostics:
        def __init__(
            self,
            *,
            logistic_converged: typing.Any,
            logistic_iteration_count: typing.Any,
            firth_iteration_count: typing.Any | None,
            firth_convergence_reason_code: typing.Any | None,
        ) -> None: ...
        @property
        def logistic_converged(self) -> typing.Any: ...
        @property
        def logistic_iteration_count(self) -> typing.Any: ...
        @property
        def firth_iteration_count(self) -> typing.Any | None: ...
        @property
        def firth_convergence_reason_code(self) -> typing.Any | None: ...

    class JaxPreparedChromosome:
        def __init__(self, *, state: object, diagnostics: engine.JaxNullModelDiagnostics | None) -> None: ...
        @property
        def state(self) -> object: ...
        @property
        def diagnostics(self) -> engine.JaxNullModelDiagnostics | None: ...

    class JaxBinaryDiagnostics:
        def __init__(
            self,
            *,
            score_only_count: int,
            score_test_candidate_count: int,
            firth_candidate_count: int,
            firth_iteration_min: int,
            firth_iteration_median: float,
            firth_iteration_max: int,
            firth_converged_count: int,
            firth_failed_count: int,
            firth_numerical_failure_count: int,
            firth_max_iteration_failure_count: int,
            firth_invalid_statistic_failure_count: int,
            firth_step_halving_failure_count: int,
            pseudo_firth_attempt_count: int,
            pseudo_firth_success_count: int,
            newton_raphson_zero_start_attempt_count: int,
            newton_raphson_zero_start_success_count: int,
            newton_raphson_warm_start_attempt_count: int,
            newton_raphson_warm_start_success_count: int,
            sparse_correction_count: int,
            dense_correction_count: int,
        ) -> None: ...

    class JaxHostAssociationBatch:
        def __init__(
            self,
            *,
            beta: typing.Any,
            standard_error: typing.Any,
            chi_squared: typing.Any,
            log10_p_value: typing.Any,
            extra_code: typing.Any | None,
            binary_diagnostics: engine.JaxBinaryDiagnostics | None,
        ) -> None: ...
        @property
        def beta(self) -> typing.Any: ...
        @property
        def standard_error(self) -> typing.Any: ...
        @property
        def chi_squared(self) -> typing.Any: ...
        @property
        def log10_p_value(self) -> typing.Any: ...
        @property
        def extra_code(self) -> typing.Any | None: ...
        @property
        def binary_diagnostics(self) -> engine.JaxBinaryDiagnostics | None: ...
