#![warn(clippy::pedantic)]

pub mod jax_runtime;
pub mod rayon_runtime;
pub mod run_events;
pub mod run_metadata;
pub mod runtime_paths;
pub mod runtime_policy;
pub mod runtime_state;
pub mod shutdown;
pub mod telemetry_policy;
pub mod telemetry_session;
pub mod timing;

pub use jax_runtime::{
    JaxDeviceObservation, JaxGpuValidationPlan, JaxRuntimeConfigUpdatePayload, JaxRuntimeConfigValue,
    JaxRuntimeDiagnosticEventPayload, JaxRuntimeDiagnosticFieldPayload, JaxRuntimeDiagnosticRecordPlan,
    JaxRuntimeDiagnosticValue, JaxRuntimeSetupPayload, JaxRuntimeSetupSideEffectPlan,
    build_jax_runtime_setup_diagnostic_events, complete_jax_runtime_setup_validation, nvidia_driver_files_are_visible,
    plan_jax_gpu_validation, plan_jax_runtime_config_updates, plan_jax_runtime_diagnostic_record,
    plan_jax_runtime_setup_side_effects, resolve_jax_runtime_setup,
};
pub use rayon_runtime::{
    RayonRuntimeError, configure_global_rayon_thread_pool, format_global_rayon_thread_pool_configuration_error,
};
pub use run_events::{
    ASSOCIATION_BACKEND_SELECTED_EVENT_NAME, AssociationBackendSelectedTelemetryFields, BGEN_ENGINE_OPENED_EVENT_NAME,
    BINARY_CORRECTION_SUMMARY_EVENT_NAME, BgenEngineOpenedTelemetryFields,
    CALLBACK_NULL_LOGISTIC_NONCONVERGENCE_WARNING_DIAGNOSTIC_EVENT_NAME, EFFECTIVE_CONFIG_WRITTEN_EVENT_NAME,
    EXECUTION_PLAN_PREPARED_EVENT_NAME, EffectiveConfigWrittenTelemetryFields, ExecutionPlanPreparedTelemetryFields,
    GPU_GENOTYPE_FORMAT_RESOLVED_EVENT_NAME, GpuGenotypeFormatResolvedTelemetryFields,
    IO_OUTPUT_RESUME_COMMITTED_CHUNKS_DIAGNOSTIC_EVENT_NAME, MULTI_PHENOTYPE_SAMPLE_SUMMARY_EVENT_NAME,
    MultiPhenotypePreflightCompletedTelemetryFields, MultiPhenotypeSampleSummaryTelemetryFields,
    MultiPhenotypeWriterFinishedTelemetryFields, NATIVE_DISPATCH_BGEN_ENGINE_CONSTRUCTING_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_BGEN_ENGINE_CONSTRUCTING_DIAGNOSTIC_MESSAGE,
    NATIVE_DISPATCH_CALLBACK_DRAIN_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_CALLBACK_DRAIN_STARTED_DIAGNOSTIC_MESSAGE, NATIVE_DISPATCH_DELIVERY_FAILED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_DELIVERY_FINISHED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_DELIVERY_INTERRUPTED_DIAGNOSTIC_EVENT_NAME, NATIVE_DISPATCH_DELIVERY_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_PIPELINE_FINISHED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_TRUSTED_BGEN_VALIDATION_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_TRUSTED_BGEN_VALIDATION_STARTED_DIAGNOSTIC_MESSAGE,
    NATIVE_DISPATCH_WRITER_SESSION_FINISH_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_WRITER_SESSION_FINISH_STARTED_DIAGNOSTIC_MESSAGE,
    NATIVE_DISPATCH_WRITER_SESSION_INTERRUPTED_FLUSH_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_WRITER_SESSIONS_FINISH_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_DISPATCH_WRITER_SESSIONS_FINISH_STARTED_DIAGNOSTIC_MESSAGE,
    NATIVE_DISPATCH_WRITER_SESSIONS_INTERRUPTED_FLUSH_STARTED_DIAGNOSTIC_EVENT_NAME,
    NATIVE_RUNTIME_KNOBS_CONFIGURED_DIAGNOSTIC_EVENT_NAME, NATIVE_RUNTIME_KNOBS_CONFIGURED_DIAGNOSTIC_MESSAGE,
    PIPELINE_GPU_GENOTYPE_FORMAT_RESOLVED_DIAGNOSTIC_EVENT_NAME,
    PIPELINE_MULTI_GROUP_PREFLIGHT_COMPLETED_DIAGNOSTIC_EVENT_NAME,
    PIPELINE_MULTI_GROUP_PREFLIGHT_COMPLETED_DIAGNOSTIC_MESSAGE,
    PIPELINE_MULTI_GROUP_PREFLIGHT_STARTED_DIAGNOSTIC_EVENT_NAME,
    PIPELINE_MULTI_GROUP_PREFLIGHT_STARTED_DIAGNOSTIC_MESSAGE,
    PIPELINE_MULTI_PHENOTYPE_SAMPLE_SUMMARY_DIAGNOSTIC_EVENT_NAME, PREDICTION_SOURCE_LOADED_EVENT_NAME,
    PREFLIGHT_COMPLETED_EVENT_NAME, PREFLIGHT_WARNING_DIAGNOSTIC_EVENT_NAME, PhenotypeWriterFinishedTelemetryFields,
    PredictionSourceLoadedTelemetryFields, RUN_COMPLETED_EVENT_NAME, RUN_FAILED_EVENT_NAME, RUN_LIFECYCLE_ERROR_LEVEL,
    RUN_LIFECYCLE_INFO_LEVEL, RUN_LIFECYCLE_WARN_LEVEL, RUN_STARTED_EVENT_NAME,
    RUNNER_BINARY_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_BINARY_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_EXECUTION_PLAN_BUILD_STARTED_DIAGNOSTIC_EVENT_NAME, RUNNER_EXECUTION_PLAN_BUILD_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_EXECUTION_PLAN_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_EXECUTION_PLAN_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_EXECUTION_PLAN_FINALIZATION_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_EXECUTION_PLAN_FINALIZATION_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_EXECUTION_PLAN_PREPARED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_JAX_RUNTIME_CONFIGURATION_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_JAX_RUNTIME_CONFIGURATION_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_LINEAR_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_LINEAR_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_METADATA_ARTIFACTS_FINALIZED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_MULTI_PHENOTYPE_BINARY_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_MULTI_PHENOTYPE_BINARY_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_MULTI_PHENOTYPE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_MULTI_PHENOTYPE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_MULTI_PHENOTYPE_LINEAR_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_MULTI_PHENOTYPE_LINEAR_ENGINE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE,
    RUNNER_REGENIE_RUN_COMPLETED_DIAGNOSTIC_EVENT_NAME, RUNNER_REGENIE_RUN_COMPLETED_DIAGNOSTIC_MESSAGE,
    RUNNER_REGENIE_RUN_FAILED_DIAGNOSTIC_EVENT_NAME, RUNNER_REGENIE_RUN_FAILED_DIAGNOSTIC_MESSAGE,
    RUNNER_REGENIE_RUN_INTERRUPTED_DIAGNOSTIC_EVENT_NAME, RUNNER_REGENIE_RUN_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_REGENIE_RUN_STARTED_DIAGNOSTIC_MESSAGE, RUNNER_SINGLE_PHENOTYPE_DISPATCH_STARTED_DIAGNOSTIC_EVENT_NAME,
    RUNNER_SINGLE_PHENOTYPE_DISPATCH_STARTED_DIAGNOSTIC_MESSAGE, RunArtifactPayload, RunArtifactTelemetryFields,
    RunCompletedEventPayload, RunCompletedTelemetryFields, RunDiagnosticEventPayload, RunDiagnosticFieldPayload,
    RunDiagnosticFieldValue, RunFailedEventPayload, RunFailedTelemetryFields, RunInterruptedEventPayload,
    RunInterruptedTelemetryFields, RunStartedTelemetryFields, RunTelemetryStringField,
    SAMPLE_ALIGNMENT_COMPLETED_EVENT_NAME, SampleAlignmentCompletedTelemetryFields,
    SingleTraitPreflightCompletedTelemetryFields, WRITER_FINISHED_EVENT_NAME, build_artifact_telemetry_fields,
    build_association_backend_selected_telemetry_fields, build_bgen_engine_opened_telemetry_fields,
    build_callback_null_logistic_nonconvergence_warning_diagnostic_payload,
    build_effective_config_written_telemetry_fields, build_execution_plan_prepared_telemetry_fields,
    build_gpu_genotype_format_resolved_telemetry_fields, build_io_output_resume_committed_chunks_diagnostic_payload,
    build_multi_phenotype_preflight_completed_telemetry_fields, build_multi_phenotype_sample_summary_telemetry_fields,
    build_multi_phenotype_writer_finished_telemetry_fields,
    build_native_dispatch_bgen_engine_constructing_diagnostic_payload,
    build_native_dispatch_callback_drain_started_diagnostic_payload,
    build_native_dispatch_delivery_failed_diagnostic_payload,
    build_native_dispatch_delivery_finished_diagnostic_payload,
    build_native_dispatch_delivery_interrupted_diagnostic_payload,
    build_native_dispatch_delivery_started_diagnostic_payload,
    build_native_dispatch_pipeline_finished_diagnostic_payload,
    build_native_dispatch_trusted_bgen_validation_started_diagnostic_payload,
    build_native_dispatch_writer_session_finish_started_diagnostic_payload,
    build_native_dispatch_writer_session_interrupted_flush_started_diagnostic_payload,
    build_native_dispatch_writer_sessions_finish_started_diagnostic_payload,
    build_native_dispatch_writer_sessions_interrupted_flush_started_diagnostic_payload,
    build_native_runtime_knobs_configured_diagnostic_payload, build_phenotype_writer_finished_telemetry_fields,
    build_pipeline_gpu_genotype_format_resolved_diagnostic_payload,
    build_pipeline_multi_group_preflight_completed_diagnostic_payload,
    build_pipeline_multi_group_preflight_started_diagnostic_payload,
    build_pipeline_multi_phenotype_sample_summary_diagnostic_payload, build_prediction_source_loaded_telemetry_fields,
    build_preflight_warning_diagnostic_payload, build_run_completed_telemetry_fields,
    build_run_failed_telemetry_fields, build_run_interrupted_telemetry_fields, build_run_started_telemetry_fields,
    build_runner_binary_engine_dispatch_started_diagnostic_payload,
    build_runner_execution_plan_build_started_diagnostic_payload,
    build_runner_execution_plan_dispatch_started_diagnostic_payload,
    build_runner_execution_plan_finalization_started_diagnostic_payload,
    build_runner_execution_plan_prepared_diagnostic_payload,
    build_runner_jax_runtime_configuration_started_diagnostic_payload,
    build_runner_linear_engine_dispatch_started_diagnostic_payload,
    build_runner_metadata_artifacts_finalized_diagnostic_payload,
    build_runner_multi_phenotype_binary_engine_dispatch_started_diagnostic_payload,
    build_runner_multi_phenotype_dispatch_started_diagnostic_payload,
    build_runner_multi_phenotype_linear_engine_dispatch_started_diagnostic_payload,
    build_runner_run_completed_diagnostic_payload, build_runner_run_failed_diagnostic_payload,
    build_runner_run_interrupted_diagnostic_payload, build_runner_run_started_diagnostic_payload,
    build_runner_single_phenotype_dispatch_started_diagnostic_payload,
    build_sample_alignment_completed_telemetry_fields, build_single_trait_preflight_completed_telemetry_fields,
    render_artifact_lines, render_run_completed_lines, render_run_failed_lines, render_run_interrupted_lines,
};
pub use run_metadata::{
    ExecutionRunArtifactsInput, PhenotypeRunArtifactsInput, RunArtifactsPayload, RunManifestCommandPayload,
    RunManifestExtensionInput, RunManifestExtensionPayload, RunManifestRuntimePayload, build_execution_run_artifacts,
    build_multi_run_artifacts, build_phenotype_run_artifacts, build_run_manifest_extension,
};
pub use runtime_paths::build_default_local_cache_directory;
pub use runtime_policy::{LoggingRuntimePolicyPayload, build_logging_runtime_policy, describe_logging_runtime_policy};
pub use runtime_state::{
    JaxRuntimePolicyPayload, JaxRuntimeSetupLifecyclePlan, ProcessRuntimeState, RayonThreadPoolConfigurationError,
    RayonThreadPoolConfigurationPlan, RunRuntime, RuntimeCompatibilityError, RuntimeCompatibilityToken,
    RuntimePolicyPayload, RuntimeStateSnapshotPayload, build_jax_runtime_policy_payload, describe_jax_runtime_policy,
};
pub use shutdown::{
    SecondSignalExceptionPlan, ShutdownControllerState, ShutdownRequestAction, ShutdownRequestDecisionPayload,
    ShutdownSignalPayload, build_shutdown_signal, default_shutdown_signal_numbers, plan_second_signal_exception,
};
pub use telemetry_policy::{
    TelemetryPathsPayload, TelemetryWriterCountersPayload, build_empty_writer_counters, format_timestamp,
    paths_refer_to_same_file, resolve_output_run_root, resolve_telemetry_paths, resolve_telemetry_stream_file,
};
pub use telemetry_session::{
    TelemetryCapAction, TelemetryCloseMetadataPayload, TelemetryClosePlan, TelemetryEventCapState,
    TelemetryEventEmissionPlan, TelemetryEventEnvelope, TelemetryProgressEmissionPlan, TelemetryProgressThrottleState,
    TelemetryWriterCounterSnapshot, build_telemetry_close_metadata, build_telemetry_event_envelope, generate_run_id,
    plan_telemetry_close, plan_telemetry_event_emission, plan_telemetry_progress_emission,
};
pub use timing::{
    ChunkStageSummary, ChunkStageTiming, FinalTimingOutputsWriteResultPayload,
    FinalTimingOutputsWriteStartedDiagnosticPayload, NullLogisticDiagnosticValue, NullLogisticSummary,
    NumericDiagnosticValue, ProfileSummaryPayload, QueueBackpressureAccumulator, QueueBackpressureKey,
    QueueBackpressureSnapshot, StageTimingRecorderPlan, StageTimingSnapshotPayload, StageTimingState, TimingFileError,
    TimingFileWritePlan, TransferMetadataAccumulator, TransferMetadataError, TransferMetadataKey,
    TransferMetadataObservation, TransferMetadataSnapshot, build_final_timing_outputs_write_started_diagnostic_payload,
    build_transfer_metadata_observation, plan_stage_timing_recorder, plan_timing_file_write,
    should_collect_exact_stage_timings, write_profile_summary_payload, write_stage_timing_snapshot_payload,
};
