[package]
name = "g-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
g-genotype = { workspace = true }
g-genotype-contracts = { workspace = true }
g-input = { workspace = true }
g-output = { workspace = true }
g-plan = { workspace = true }
g-runtime = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
