use super::{DefaultPolicy, OptionSpec, OptionValueType, SupportLevel};

pub(super) const OPTION_SPECS: &[OptionSpec] = &[
    OptionSpec {
        cli_name: "step",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "REGENIE analysis step. Only step 2 is supported.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "qt",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Analyze quantitative traits.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "bt",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Analyze binary traits.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "bgen",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "BGEN genotype file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "sample",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "BGEN sample file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "phenoFile",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype table.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "phenoCol",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype column.",
        value_type: OptionValueType::String,
        multiple: true,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "phenoColList",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype column list.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "covarFile",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate table.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "covarCol",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate column.",
        value_type: OptionValueType::String,
        multiple: true,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "covarColList",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate column list.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "pred",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "REGENIE step 1 prediction list.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "bsize",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Variants per processing block.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "threads",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Requested CPU thread count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "out",
        support_level: SupportLevel::Supported,
        section: "output",
        help_text: "Output prefix.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "firth",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use Firth fallback.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "approx",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use approximate Firth fallback.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "pThresh",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Fallback p-value threshold.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth-se",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use Firth-derived standard errors.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-device",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "JAX execution device.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["cpu", "gpu"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-staging-depth",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Positive native callback staging depth.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-variant-limit",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Debug variant cap.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-trusted-no-missing-diploid",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Use the trusted BGEN no-missing diploid fast path.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-trusted-bgen-validation-mode",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Trusted BGEN validation mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["cache_on_miss", "force_validate", "assume_validated"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-sample-key-mode",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Sample key mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["iid", "fid_iid"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-multi-phenotype-sample-mode",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Multi-phenotype sample mode. complete-case batches phenotypes on the shared complete-case intersection and is not equivalent to separate single-phenotype REGENIE runs.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["per-phenotype", "complete-case"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-output-format",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Output materialization format.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["parquet", "arrow", "regenie"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-output-run-directory",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Internal run directory.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-writer-threads",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Output writer thread count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-writer-queue-depth",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Output writer queue depth.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-resume",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Resume a previous run.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-resume-mode",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Resume validation mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["fast", "strict"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-finalize-parquet",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Finalize Parquet output.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-batch-size",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth batch size.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-candidate-capacity",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth candidate capacity.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-binary-null-maximum-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum null-logistic iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-binary-null-coefficient-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Null-logistic coefficient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-logistic-nonconvergence",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Policy when a binary null-logistic chromosome fit does not converge.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["fail", "warn"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-binary-minimum-probability",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Binary logistic probability clipping floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-binary-minimum-variance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Binary variance and information-matrix numerical floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-binary-relative-variance-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Relative score-test variance floor multiplier.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-linear-minimum-variance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Linear residualized genotype variance numerical floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-linear-relative-variance-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Relative linear residualized genotype variance floor multiplier.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-maximum-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-gradient-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth gradient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-coefficient-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth coefficient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-likelihood-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth likelihood tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-maximum-step-size",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Firth maximum step size.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-pseudo-maximum-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum outer pseudo-Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-pseudo-inner-maximum-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum inner pseudo-Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-newton-raphson-zero-start-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum zero-start scalar Firth Newton-Raphson iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-line-search-maximum-attempts",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum scalar Firth line-search attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-step-halving-maximum-attempts",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum Firth step-halving attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-initial-response-scale",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Pseudo-response scale for block full-model Firth initialization.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-sparse-carrier-dosage-threshold",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Raw dosage threshold for sparse carrier-only Firth samples.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-step-halving-scale",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Full-model Firth step multiplier after each rejected backtracking attempt.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-maximum-iterations",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum covariate-only null Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-gradient-tolerance",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Covariate-only null Firth gradient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-maximum-step-size",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Covariate-only null Firth maximum step size.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-fallback-iteration-multiplier",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Covariate-only null Firth fallback iteration multiplier.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-fallback-step-divisor",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Covariate-only null Firth fallback step divisor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-line-search-maximum-attempts",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Maximum covariate-only null Firth line-search attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-null-firth-step-halving-scale",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Null Firth step multiplier after each rejected line-search attempt.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-use-block-firth-math",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Use block-oriented Firth math.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-bgen-decode-tile-variant-count",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Native BGEN decode tile variant count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-gpu-genotype-format",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "GPU genotype transfer format.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["dosage", "packed8"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-score-dtype",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Internal JAX score-test compute dtype; public result statistics remain float32.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "float64"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-firth-dtype",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Internal Firth compute dtype; only float64 is supported. Public result statistics remain float32.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "float64"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-jax-cache-dir",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "JAX cache directory.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-jax-matmul-precision",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "JAX matmul precision.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "tensorfloat32", "bfloat16", "highest"],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-jax-persistent-cache",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Enable the JAX persistent compilation cache.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-jax-persistent-cache-min-entry-size-bytes",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Minimum JAX persistent-cache entry size.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-jax-persistent-cache-min-compile-time-seconds",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Minimum JAX compile time for persistent-cache writes.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-jax-xla-autotune-cache",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Enable node-local XLA autotune caches.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-jax-transfer-guard",
        support_level: SupportLevel::GExtension,
        section: "g.compute",
        help_text: "Enable JAX transfer-guard diagnostics.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-output-chunks-per-arrow-file",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Number of engine chunks grouped into one Arrow file or Parquet part.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-output-arrow-compression",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Arrow IPC compression for internal chunk files.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["zstd", "none"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-output-parquet-compression",
        support_level: SupportLevel::GExtension,
        section: "g.output",
        help_text: "Parquet compression for dataset part files.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["zstd", "none"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-telemetry",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Run telemetry mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["off", "progress", "profile", "trace"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-log-dir",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Directory for run telemetry logs.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-stage-timings-json",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Write stage timing diagnostics to JSON.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-log-filter",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Rust/Python tracing filter.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-log-file",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Write Rust JSONL tracing logs to this file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-log-stderr",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Write compact tracing logs to stderr.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-progress-interval-seconds",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Minimum seconds between progress telemetry events.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-progress-interval-chunks",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Minimum chunks between progress telemetry events.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-profile-summary-json",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Write aggregate profile summary JSON.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-trace-file",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Write high-volume Rust trace JSONL events to this file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "g-trace-filter",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Rust tracing filter for the trace file.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-trace-event-cap",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Maximum trace-mode JSONL events; 0 disables the cap.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-log-queue-size",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Buffered line count for non-blocking log writers.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-log-lossy",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Drop logs instead of blocking when the log queue is full.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-include-source-location",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Include source file and line in JSON tracing events.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "g-include-span-events",
        support_level: SupportLevel::GExtension,
        section: "g.diagnostics",
        help_text: "Include tracing span lifecycle events.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
];
