use super::{DefaultPolicy, OptionSpec, OptionValueType, SupportLevel};

pub(super) const OPTION_SPECS: &[OptionSpec] = &[
    OptionSpec {
        cli_name: "step",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "REGENIE analysis step. Only step 2 is supported.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "qt",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Analyze quantitative traits.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "bt",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Analyze binary traits.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "bgen",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "BGEN genotype file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "sample",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "BGEN sample file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "phenoFile",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype table.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "phenoCol",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype column.",
        value_type: OptionValueType::String,
        multiple: true,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "phenoColList",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Phenotype column list.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "covarFile",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate table.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "covarCol",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate column.",
        value_type: OptionValueType::String,
        multiple: true,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "covarColList",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "Covariate column list.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "pred",
        support_level: SupportLevel::Supported,
        section: "input",
        help_text: "REGENIE step 1 prediction list.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "bsize",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Variants per processing block.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "threads",
        support_level: SupportLevel::Supported,
        section: "trait",
        help_text: "Requested CPU thread count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "out",
        support_level: SupportLevel::Supported,
        section: "output",
        help_text: "Output prefix.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::RequiredAtRuntime,
    },
    OptionSpec {
        cli_name: "firth",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use Firth fallback.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "approx",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use approximate Firth fallback.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "pThresh",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Fallback p-value threshold.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth-se",
        support_level: SupportLevel::Supported,
        section: "binary",
        help_text: "Use Firth-derived standard errors.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "device",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "JAX execution device.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["cpu", "gpu"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "staging_depth",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Positive native callback staging depth.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "variant_limit",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Debug variant cap.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "trusted_no_missing_diploid",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Use the trusted BGEN no-missing diploid fast path.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "trusted_bgen_validation_mode",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Trusted BGEN validation mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["cache_on_miss", "force_validate", "assume_validated"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "sample_key_mode",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Sample key mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["iid", "fid_iid"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "multi_phenotype_sample_mode",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Multi-phenotype sample mode. complete-case batches phenotypes on the shared complete-case intersection and is not equivalent to separate single-phenotype REGENIE runs.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["per-phenotype", "complete-case"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "format",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Output materialization format.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["parquet", "arrow", "regenie"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "output_run_directory",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Internal run directory.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "writer_threads",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Output writer thread count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "writer_queue_depth",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Output writer queue depth.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "resume",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Resume a previous run.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "resume_mode",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Resume validation mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["fast", "strict"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "finalize_parquet",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Finalize Parquet output.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_batch_size",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth batch size.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_candidate_capacity",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth candidate capacity.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "binary_null_maximum_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum null-logistic iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "binary_null_coefficient_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Null-logistic coefficient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_logistic_nonconvergence_policy",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Policy when a binary null-logistic chromosome fit does not converge.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["fail", "warn"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "binary_minimum_probability",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Binary logistic probability clipping floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "binary_minimum_variance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Binary variance and information-matrix numerical floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "binary_relative_variance_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Relative score-test variance floor multiplier.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "linear_minimum_variance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Linear residualized genotype variance numerical floor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "linear_relative_variance_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Relative linear residualized genotype variance floor multiplier.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_maximum_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_gradient_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth gradient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_coefficient_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth coefficient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_likelihood_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth likelihood tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_maximum_step_size",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Firth maximum step size.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_pseudo_maximum_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum outer pseudo-Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_pseudo_inner_maximum_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum inner pseudo-Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_newton_raphson_zero_start_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum zero-start scalar Firth Newton-Raphson iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_line_search_maximum_attempts",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum scalar Firth line-search attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_step_halving_maximum_attempts",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum Firth step-halving attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_initial_response_scale",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Pseudo-response scale for block full-model Firth initialization.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_sparse_carrier_dosage_threshold",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Raw dosage threshold for sparse carrier-only Firth samples.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_step_halving_scale",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Full-model Firth step multiplier after each rejected backtracking attempt.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_maximum_iterations",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum covariate-only null Firth iterations.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_gradient_tolerance",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Covariate-only null Firth gradient tolerance.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_maximum_step_size",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Covariate-only null Firth maximum step size.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_fallback_iteration_multiplier",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Covariate-only null Firth fallback iteration multiplier.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_fallback_step_divisor",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Covariate-only null Firth fallback step divisor.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_line_search_maximum_attempts",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Maximum covariate-only null Firth line-search attempts.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "null_firth_step_halving_scale",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Null Firth step multiplier after each rejected line-search attempt.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "use_block_firth_math",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Use block-oriented Firth math.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "bgen_decode_tile_variant_count",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Native BGEN decode tile variant count.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "gpu_genotype_format",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "GPU genotype transfer format.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["dosage", "packed8"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "score_dtype",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Internal JAX score-test compute dtype; public result statistics remain float32.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "float64"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "firth_dtype",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Internal Firth compute dtype; only float64 is supported. Public result statistics remain float32.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "float64"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "jax_cache_dir",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "JAX cache directory.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "jax_matmul_precision",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "JAX matmul precision.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["float32", "tensorfloat32", "bfloat16", "highest"],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "jax_persistent_cache",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Enable the JAX persistent compilation cache.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "jax_persistent_cache_min_entry_size_bytes",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Minimum JAX persistent-cache entry size.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "jax_persistent_cache_min_compile_time_seconds",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Minimum JAX compile time for persistent-cache writes.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "jax_xla_autotune_cache",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Enable node-local XLA autotune caches.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "jax_transfer_guard",
        support_level: SupportLevel::GExtension,
        section: "compute",
        help_text: "Enable JAX transfer-guard diagnostics.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "chunks_per_arrow_file",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Number of engine chunks grouped into one Arrow file or Parquet part.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "arrow_compression",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Arrow IPC compression for internal chunk files.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["zstd", "none"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "parquet_compression",
        support_level: SupportLevel::GExtension,
        section: "output",
        help_text: "Parquet compression for dataset part files.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["zstd", "none"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "telemetry",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Run telemetry mode.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &["off", "progress", "profile", "trace"],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "log_dir",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Directory for run telemetry logs.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "stage_timings_json",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Write stage timing diagnostics to JSON.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "log_filter",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Rust/Python tracing filter.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "log_file",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Write Rust JSONL tracing logs to this file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "log_stderr",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Write compact tracing logs to stderr.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "progress_interval_seconds",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Minimum seconds between progress telemetry events.",
        value_type: OptionValueType::Float,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "progress_interval_chunks",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Minimum chunks between progress telemetry events.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "profile_summary_json",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Write aggregate profile summary JSON.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "trace_file",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Write high-volume Rust trace JSONL events to this file.",
        value_type: OptionValueType::Path,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::AbsentIsNone,
    },
    OptionSpec {
        cli_name: "trace_filter",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Rust tracing filter for the trace file.",
        value_type: OptionValueType::String,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "trace_event_cap",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Maximum trace-mode JSONL events; 0 disables the cap.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "log_queue_size",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Buffered line count for non-blocking log writers.",
        value_type: OptionValueType::Integer,
        multiple: false,
        is_flag: false,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "log_lossy",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Drop logs instead of blocking when the log queue is full.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "include_source_location",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Include source file and line in JSON tracing events.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
    OptionSpec {
        cli_name: "include_span_events",
        support_level: SupportLevel::GExtension,
        section: "diagnostics",
        help_text: "Include tracing span lifecycle events.",
        value_type: OptionValueType::Boolean,
        multiple: false,
        is_flag: true,
        accepted_values: &[],
        default_policy: DefaultPolicy::Value,
    },
];
