use super::metadata::{OptionSpec, OptionValueKind};

const fn value(
    cli_name: &'static str,
    section: &'static str,
    help_text: &'static str,
    value_kind: OptionValueKind,
) -> OptionSpec {
    OptionSpec { cli_name, section, help_text, value_kind, multiple: false, is_flag: false }
}

const fn repeated(cli_name: &'static str, section: &'static str, help_text: &'static str) -> OptionSpec {
    OptionSpec { cli_name, section, help_text, value_kind: OptionValueKind::String, multiple: true, is_flag: false }
}

const fn flag(cli_name: &'static str, section: &'static str, help_text: &'static str) -> OptionSpec {
    OptionSpec { cli_name, section, help_text, value_kind: OptionValueKind::Boolean, multiple: false, is_flag: true }
}

pub(crate) const OPTION_SPECS: &[OptionSpec] = &[
    value("step", "trait", "REGENIE analysis step. Only step 2 is supported.", OptionValueKind::Integer),
    flag("qt", "trait", "Analyze quantitative traits."),
    flag("bt", "trait", "Analyze binary traits."),
    value("bgen", "input", "BGEN genotype file.", OptionValueKind::Path),
    value("sample", "input", "BGEN sample file.", OptionValueKind::Path),
    value("phenoFile", "input", "Phenotype table.", OptionValueKind::Path),
    repeated("phenoCol", "input", "Phenotype column."),
    value("phenoColList", "input", "Phenotype column list.", OptionValueKind::String),
    value("covarFile", "input", "Covariate table.", OptionValueKind::Path),
    repeated("covarCol", "input", "Covariate column."),
    value("covarColList", "input", "Covariate column list.", OptionValueKind::String),
    value("pred", "input", "REGENIE step 1 prediction list.", OptionValueKind::Path),
    value("bsize", "trait", "Variants per processing block.", OptionValueKind::Integer),
    value("threads", "trait", "Requested CPU thread count.", OptionValueKind::Integer),
    value("out", "output", "Output prefix.", OptionValueKind::Path),
    flag("firth", "binary", "Use Firth fallback."),
    flag("approx", "binary", "Use approximate Firth fallback."),
    value("pThresh", "binary", "Fallback p-value threshold.", OptionValueKind::Float),
    flag("firth-se", "binary", "Use Firth-derived standard errors."),
    value("device", "compute", "JAX execution device.", OptionValueKind::String),
    value("staging_depth", "compute", "Positive native callback staging depth.", OptionValueKind::Integer),
    value("variant_limit", "compute", "Debug variant cap.", OptionValueKind::Integer),
    flag("trusted_no_missing_diploid", "compute", "Use the trusted BGEN no-missing diploid fast path."),
    value("trusted_bgen_validation_mode", "compute", "Trusted BGEN validation mode.", OptionValueKind::String),
    value("sample_key_mode", "compute", "Sample key mode.", OptionValueKind::String),
    value(
        "multi_phenotype_sample_mode",
        "compute",
        "Multi-phenotype sample mode. complete-case batches phenotypes on the shared complete-case intersection and is not equivalent to separate single-phenotype REGENIE runs.",
        OptionValueKind::String,
    ),
    value("format", "output", "Output materialization format.", OptionValueKind::String),
    value("output_run_directory", "output", "Internal run directory.", OptionValueKind::Path),
    value("writer_threads", "output", "Output writer thread count.", OptionValueKind::Integer),
    value("writer_queue_depth", "output", "Output writer queue depth.", OptionValueKind::Integer),
    flag("resume", "output", "Resume a previous run."),
    value("resume_mode", "output", "Resume validation mode.", OptionValueKind::String),
    flag("finalize_parquet", "output", "Finalize Parquet output."),
    value("firth_batch_size", "compute", "Firth batch size.", OptionValueKind::Integer),
    value("firth_candidate_capacity", "compute", "Firth candidate capacity.", OptionValueKind::Integer),
    value("binary_null_maximum_iterations", "compute", "Maximum null-logistic iterations.", OptionValueKind::Integer),
    value(
        "binary_null_coefficient_tolerance",
        "compute",
        "Null-logistic coefficient tolerance.",
        OptionValueKind::Float,
    ),
    value(
        "null_logistic_nonconvergence_policy",
        "compute",
        "Policy when a binary null-logistic chromosome fit does not converge.",
        OptionValueKind::String,
    ),
    value(
        "binary_minimum_probability",
        "compute",
        "Binary logistic probability clipping floor.",
        OptionValueKind::Float,
    ),
    value(
        "binary_minimum_variance",
        "compute",
        "Binary variance and information-matrix numerical floor.",
        OptionValueKind::Float,
    ),
    value(
        "binary_relative_variance_tolerance",
        "compute",
        "Relative score-test variance floor multiplier.",
        OptionValueKind::Float,
    ),
    value(
        "linear_minimum_variance",
        "compute",
        "Linear residualized genotype variance numerical floor.",
        OptionValueKind::Float,
    ),
    value(
        "linear_relative_variance_tolerance",
        "compute",
        "Relative linear residualized genotype variance floor multiplier.",
        OptionValueKind::Float,
    ),
    value("firth_maximum_iterations", "compute", "Maximum Firth iterations.", OptionValueKind::Integer),
    value("firth_gradient_tolerance", "compute", "Firth gradient tolerance.", OptionValueKind::Float),
    value("firth_coefficient_tolerance", "compute", "Firth coefficient tolerance.", OptionValueKind::Float),
    value("firth_likelihood_tolerance", "compute", "Firth likelihood tolerance.", OptionValueKind::Float),
    value("firth_maximum_step_size", "compute", "Firth maximum step size.", OptionValueKind::Float),
    value(
        "firth_pseudo_maximum_iterations",
        "compute",
        "Maximum outer pseudo-Firth iterations.",
        OptionValueKind::Integer,
    ),
    value(
        "firth_pseudo_inner_maximum_iterations",
        "compute",
        "Maximum inner pseudo-Firth iterations.",
        OptionValueKind::Integer,
    ),
    value(
        "firth_newton_raphson_zero_start_iterations",
        "compute",
        "Maximum zero-start scalar Firth Newton-Raphson iterations.",
        OptionValueKind::Integer,
    ),
    value(
        "firth_line_search_maximum_attempts",
        "compute",
        "Maximum scalar Firth line-search attempts.",
        OptionValueKind::Integer,
    ),
    value(
        "firth_step_halving_maximum_attempts",
        "compute",
        "Maximum Firth step-halving attempts.",
        OptionValueKind::Integer,
    ),
    value(
        "firth_initial_response_scale",
        "compute",
        "Pseudo-response scale for block full-model Firth initialization.",
        OptionValueKind::Float,
    ),
    value(
        "firth_sparse_carrier_dosage_threshold",
        "compute",
        "Raw dosage threshold for sparse carrier-only Firth samples.",
        OptionValueKind::Float,
    ),
    value(
        "firth_step_halving_scale",
        "compute",
        "Full-model Firth step multiplier after each rejected backtracking attempt.",
        OptionValueKind::Float,
    ),
    value(
        "null_firth_maximum_iterations",
        "compute",
        "Maximum covariate-only null Firth iterations.",
        OptionValueKind::Integer,
    ),
    value(
        "null_firth_gradient_tolerance",
        "compute",
        "Covariate-only null Firth gradient tolerance.",
        OptionValueKind::Float,
    ),
    value(
        "null_firth_maximum_step_size",
        "compute",
        "Covariate-only null Firth maximum step size.",
        OptionValueKind::Float,
    ),
    value(
        "null_firth_fallback_iteration_multiplier",
        "compute",
        "Covariate-only null Firth fallback iteration multiplier.",
        OptionValueKind::Integer,
    ),
    value(
        "null_firth_fallback_step_divisor",
        "compute",
        "Covariate-only null Firth fallback step divisor.",
        OptionValueKind::Float,
    ),
    value(
        "null_firth_line_search_maximum_attempts",
        "compute",
        "Maximum covariate-only null Firth line-search attempts.",
        OptionValueKind::Integer,
    ),
    value(
        "null_firth_step_halving_scale",
        "compute",
        "Null Firth step multiplier after each rejected line-search attempt.",
        OptionValueKind::Float,
    ),
    flag("use_block_firth_math", "compute", "Use block-oriented Firth math."),
    value(
        "bgen_decode_tile_variant_count",
        "compute",
        "Native BGEN decode tile variant count.",
        OptionValueKind::Integer,
    ),
    value("gpu_genotype_format", "compute", "GPU genotype transfer format.", OptionValueKind::String),
    value(
        "score_dtype",
        "compute",
        "Internal JAX score-test compute dtype; public result statistics remain float32.",
        OptionValueKind::String,
    ),
    value(
        "firth_dtype",
        "compute",
        "Internal Firth compute dtype; only float64 is supported. Public result statistics remain float32.",
        OptionValueKind::String,
    ),
    value("jax_cache_dir", "compute", "JAX cache directory.", OptionValueKind::Path),
    value("jax_matmul_precision", "compute", "JAX matmul precision.", OptionValueKind::String),
    flag("jax_persistent_cache", "compute", "Enable the JAX persistent compilation cache."),
    value(
        "jax_persistent_cache_min_entry_size_bytes",
        "compute",
        "Minimum JAX persistent-cache entry size.",
        OptionValueKind::Integer,
    ),
    value(
        "jax_persistent_cache_min_compile_time_seconds",
        "compute",
        "Minimum JAX compile time for persistent-cache writes.",
        OptionValueKind::Integer,
    ),
    flag("jax_xla_autotune_cache", "compute", "Enable node-local XLA autotune caches."),
    flag("jax_transfer_guard", "compute", "Enable JAX transfer-guard diagnostics."),
    value(
        "chunks_per_arrow_file",
        "output",
        "Number of engine chunks grouped into one Arrow file or Parquet part.",
        OptionValueKind::Integer,
    ),
    value("arrow_compression", "output", "Arrow IPC compression for internal chunk files.", OptionValueKind::String),
    value("parquet_compression", "output", "Parquet compression for dataset part files.", OptionValueKind::String),
    value("telemetry", "diagnostics", "Run telemetry mode.", OptionValueKind::String),
    value("log_dir", "diagnostics", "Directory for run telemetry logs.", OptionValueKind::Path),
    value("stage_timings_json", "diagnostics", "Write stage timing diagnostics to JSON.", OptionValueKind::Path),
    value("log_filter", "diagnostics", "Rust/Python tracing filter.", OptionValueKind::String),
    value("log_file", "diagnostics", "Write Rust JSONL tracing logs to this file.", OptionValueKind::Path),
    flag("log_stderr", "diagnostics", "Write compact tracing logs to stderr."),
    value(
        "progress_interval_seconds",
        "diagnostics",
        "Minimum seconds between progress telemetry events.",
        OptionValueKind::Float,
    ),
    value(
        "progress_interval_chunks",
        "diagnostics",
        "Minimum chunks between progress telemetry events.",
        OptionValueKind::Integer,
    ),
    value("profile_summary_json", "diagnostics", "Write aggregate profile summary JSON.", OptionValueKind::Path),
    value(
        "trace_file",
        "diagnostics",
        "Write high-volume Rust trace JSONL events to this file.",
        OptionValueKind::Path,
    ),
    value("trace_filter", "diagnostics", "Rust tracing filter for the trace file.", OptionValueKind::String),
    value(
        "trace_event_cap",
        "diagnostics",
        "Maximum trace-mode JSONL events; 0 disables the cap.",
        OptionValueKind::Integer,
    ),
    value(
        "log_queue_size",
        "diagnostics",
        "Buffered line count for non-blocking log writers.",
        OptionValueKind::Integer,
    ),
    flag("log_lossy", "diagnostics", "Drop logs instead of blocking when the log queue is full."),
    flag("include_source_location", "diagnostics", "Include source file and line in JSON tracing events."),
    flag("include_span_events", "diagnostics", "Include tracing span lifecycle events."),
];
